set(rpicar_SETUP_PY_SETUP_MODULE "distutils.core")
set(rpicar_SETUP_PY_VERSION "0.0.0")
set(rpicar_SETUP_PY_SCRIPTS "")
set(rpicar_SETUP_PY_PACKAGES "rpicar")
set(rpicar_SETUP_PY_PACKAGE_DIRS "src/rpicar")
set(rpicar_SETUP_PY_MODULES "")
set(rpicar_SETUP_PY_MODULE_DIRS "")